.\" Hey, EMACS: -*- nroff -*-

.\" Filename: dn-load-clipboard.1
.\" Author:   David Nebauer
.\" History:  2021-01-09 - created

.\" -----------------------------------------------------------------
.\" NOTES
.\" -----------------------------------------------------------------
.ig

For header (.TH), first parameter, NAME, should be all caps
Second parameter, SECTION, should be 1-8, maybe w/ subsection
Other parameters are allowed: see man(7), man(1)
Please adjust the date whenever revising the manpage.

Some roff macros, for reference:
.nh        disable hyphenation
.hy        enable hyphenation
.ad l      left justify
.ad b      justify to both left and right margins
.nf        disable filling
.fi        enable filling
.br        insert line break
.sp <n>    insert n+1 empty lines
for manpage-specific macros, see groff_man(7) and man(7)

Formatting [see groff_char (7) and man (7) for details]:
\(aq  : escape sequence for (')
\[dq] : plain double quote
\[lq] : left/open double quote
\[rq] : right/close double quote
`     : left/open single quote
'     : right/close single quote
\(em  : escape sequence for em dash
\(en  : escape sequence for en dash
\.    : escape sequence for period/dot
\(rg  : registration symbol
\(tm  : trademark symbol
\fX   : escape sequence that changes font, where 'X' can be 'R|I|B|BI'
        (R = roman/normal | I = italic | B = bold | BI = bold-italic)
\fP   : switch to previous font
        in this case '\fR' could also have been used
.B    : following arguments are boldened
.I    : following arguments are italicised
.BI   : following arguments are bold alternating with italics
.BR   : following arguments are bold alternating with roman
.IB   : following arguments are italics alternating with bold
.IR   : following arguments are italics alternating with roman
.RB   : following arguments are roman alternating with bold
.RI   : following arguments are roman alternating with italics
.SM   : following arguments are small (scaled 9/10 of the regular size)
.SB   : following arguments are small bold (not small alternating with bold)
        [note: if argument in alternating pattern contains whitespace,
               enclose in whitespace]
.RS x : indent following lines by x characters
.RE   : end indent

Bulleted list:
   A bulleted list:
   .IP \[bu] 2
   lawyers
   .IP \[bu]
   guns
   .IP \[bu]
   money
Numbered list:
   .nr step 1 1
   A numbered list:
   .IP \n[step] 3
   lawyers
   .IP \n+[step]
   guns
   .IP \n+[step]
   money
..

.\" -----------------------------------------------------------------
.\" SETUP
.\" -----------------------------------------------------------------

.\" Macro: Format URL
.\"  usage:  .URL "http:\\www.gnu.org" "GNU Project" " of the"
.\"  params: 1 = url
.\"          2 = link text/name
.\"          3 = postamble (optional)
.\"  note:   The www.tmac macro provides a .URL macro package; this
.\"          is a local fallback in case www.tmac is unavailable
.\"  credit: man(7)
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..

.\" Prefer .URL macro from www.tmac macro package if it is available
.\"  note: In the conditional below the '\n' escape returns the value of
.\"        a register, in this the '.g'
.\"        The '.g' register is only found in GNU 'troff', and it is
.\"        assumed that GNU troff will always include the www.tmac
.\"        macro package
.if \n[.g] .mso www.tmac

.\" Macro: Ellipsis
.\"  usage: .ellipsis
.\"  note: only works at beginning of line
.de ellipsis
.cc ^
...
^cc
..

.\" String: Command name
.ds self dn-load-clipboard

.\" -----------------------------------------------------------------
.\" MANPAGE CONTENT
.\" -----------------------------------------------------------------

.TH "DN-LOAD-CLIPBOARD" "1" "2022-03-13" "" "DN-LOAD-CLIPBOARD Manual"
.SH "NAME"
\*[self] \- load selected value into system clipboard
.SH "SYNOPSIS"
.BR "\*[self] "
.SH "DESCRIPTION"
The user selects from menus of pre-defined options. The selected option is
loaded into the system clipboard.
.PP
A submenu is indicated by an option with an appended '-->'. Selecting such an
option opens a submenu.
.PP
Menu options have a two character prefix to enable quick option selection: the
characters are chosen so that typing them highlights that entry for selection.
.PP
The current set of options is:
.PP
.RS 2
ii: david@nebauer.id.au
.br
nn: David Nebauer
.br
uu: david_nebauer
.br
dd: Date -->
.RE
.RS 6
.br
ff: Full date
.br
nn: Full date with no-break spaces
.br
ii: ISO 8601 date
.br
rr: RFC Email date
.RE
.RS 2
.br
ee: Email -->
.RE
.RS 6
.br
ii: david@nebauer.id.au
.br
ww: david.nebauer@nt.gov.au
.br
gg: davidnebauer@gmail.com
.br
bb: davidnebauer3@bigpond.com
.br
hh: davidnebauer@hotkey.net.au
.RE
.RS 2
.br
aa: Address -->
.RE
.RS 6
.br
pp: Shop 1, 4 Rowling Street, Parcel Locker 10108 96917, Casuarina NT 0810
.br
hh: 3 McColl St, Unit 4, Fannie Bay NT 0820
.br
cc: Level 1B, Casuarina Plaza, 258 Trower Road, Casuarina NT 0810
.br
rr: Central Registry, Royal Darwin Hospital, 105 Rocklands Drive, Tiwi NT 0810
.br
mm: PO Box 41326, Casuarina NT 0811
.RE
.SH "OPTIONS"
.TP
.B "\-h"
Display help.
.SH "AUTHOR"
\*[self] was written by David Nebauer (david at nebauer dot org).
.PP
This manual page was written by David Nebauer (david at nebauer dot org)
for the Debian project (but may be used by others).
