#!/usr/bin/perl

use Moo;
use strictures 2;
use 5.006;
use 5.038_001;
use version; our $VERSION = qv('0.5');
use namespace::clean;    # }}}1
use App::Dn::PkgUpdate;

App::Dn::PkgUpdate->new_with_options->run;

# POD    {{{1

__END__

=head1 NAME

dn-pkg-update - update existing, and install new, debian packages

=head1 USAGE

B<dn-pkg-update> [ I<-i> ] [ I<-f> ]

B<dn-pkg-update -h>

=head1 DESCRIPTION

Gives user an opportunity to update existing packages and potentially install
additional packages.

This script runs the following commands in sequence:

=over

=item C<dn-local-apt-repository-update-all-dirs>

=item C<aptitude update>

=item C<aptitude --autoclean-on-startup>

=item C<aptitude install>

=back

Package management is a superuser activity. If the user is not root the package
management commands are run with C<sudo>.

=head1 CONFIGURATION

There is no script configuration.

=head1 REQUIRED ARGUMENTS

None.

=head1 OPTIONS

=head2 -f | --final_prompt

Display a prompt when finished. Designed for use when called inside a new
terminal, to allow for the user to see feedback before the terminal closes.
Flag. Optional. Default: false.

=head2 -i | --ignore_failure

Whether to continue with further commands after a command fails. Flag.
Optional. Default: false.

=head2 -h | --help

Display help and exit. Flag. Optional. Default: false.

=head1 EXIT STATUS

The exit code is 0 for successful execution and 1 if the script does a
controlled exit following an error. If the script crashes unexpectedly
the error code is that given by the system.

=head1 DIAGNOSTICS

This script emits no custom warnings or error, though dependent modules may do
so.

=head1 INCOMPATIBILITIES

There are no known incompatibilities.

=head1 BUGS AND LIMITATIONS

Please report any bugs to the author.

=head1 DEPENDENCIES

=head2 Perl modules

App::Dn::PkgUpdate, Moo, namespace::clean, strictures, version.

=head2 Executables

aptitude, dn-local-apt-repository-update-all-dirs, perl, sudo.

=head1 AUTHOR

David Nebauer S<< <david@nebauer.org> >>

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2024 David Nebauer S<< <david@nebauer.org> >>

This script is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

# vim:fdm=marker
