#!/usr/bin/env bash

# File: dn-debian-iso-update
# Author: David Nebauer (david at nebauer dot org)
# Purpose: update debian iso images
# Created: 2021-01-10

# ERROR HANDLING    {{{1

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset
# Catch error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail
# Turn on traces, useful while debugging but commented out by default
# set -o xtrace

# VARIABLES    {{{1

# shellcheck disable=SC1091
source '@libexec_dir@/libdncommon-bash/liball' # supplies functions
# provided by libdncommon-bash: dn_self,dn_divider[_top|_bottom]
# shellcheck disable=SC2154
system_conf='@pkgconf_dir@/@pkg@.rc'
usage='Usage:'
# shellcheck disable=SC2046
printf -v 'usage_indent' -- ' %.s' $(eval echo "{1..${#usage}}")
parameters='[ -l int ] [ -u int ] [-v] [-d]'
# required tools findable on system path
required_system_tools=(
  cp
  getopt
  grep
  jigdo-lite
  mount
  sed
  wget
  umount
)
# required tools specified by full path
required_local_tools=()
# configurable variables
file_base= # common stem of jigdo/template/iso file names
dir_files= # directory containing jigdo/template/iso files
url_base=  # url to server directory with jigdo/template files
mnt_base=  # base mount directory
# variables that can be passed to script
lower=0
upper=0
# other vars
min_upper_iso_num=26 # upper iso image number at time of editing
unset msg
# }}}1

# PROCEDURES

# checkPrereqs()    {{{1
#   intent: check for required tools
#   params: nil
#   prints: error message if tool(s) missing
#   return: n/a, aborts scipts on failure
checkPrereqs() {
  local missing tool
  missing=()
  # these tools can be found on the base system path
  for tool in "${required_system_tools[@]}"; do
    command -v "$tool" &>/dev/null || missing+=("$tool")
  done
  # these tools are specified by absolute path
  for tool in "${required_local_tools[@]}"; do
    [[ -x "$tool" ]] || missing+=("$tool")
  done
  if [[ ${#missing[@]} -ne 0 ]]; then
    local msg
    msg="Can't run without: $(joinBy ', ' "${missing[@]}")"
    echo "${dn_self:?}: $msg" >/dev/stderr
    log "$msg" 'err'
    exit 1
  fi
}
# displayUsage()    {{{1
#   intent: display usage information
#   params: nil
#   prints: nil
#   return: nil
displayUsage() {
  cat <<_USAGE
$dn_self: Update debian iso images using jigdo

Updates debian iso image files created using jigdo. Requires
an existing iso image setup, including the files being
mounted.

The script makes a number of assumptions about the iso
image configuration. See the manpage for details.

$usage $dn_self $parameters
$usage_indent $dn_self -h

Options: -l OPT = lowest iso image number to process [int]
         -u OPT = highest iso image number to process [int]
         -v     = print input lines as they are read
                  (equivalent to 'set -o verbose')
         -d     = print input lines after command expansion
                  (equivalent to 'set -o xtrace')
_USAGE
}
# processConfigFiles([global_fp[, local_fp]])    {{{1
#   intent: process configuration files
#   params: global_fp - global config filepath (optional)
#           local_fp  - local config filepath (optional)
#   prints: nil
#   return: nil
#   notes:  set variables [  ]
processConfigFiles() {
  # set variables
  local conf name val
  local system_conf
  system_conf="$(dnNormalisePath "$1")"
  # process config files
  [[ "$(shopt extglob || true)" == 'extglob        	on' ]] && extglob_was_set=0 || extglob_was_set=1
  shopt -s extglob
  for conf in $system_conf; do
    if [ -r "$conf" ]; then
      while read -r name val; do
        if [ -n "$val" ]; then
          # remove enclosing quotes if present
          val="$(dnStripEnclosingQuotes "$val")"
          # load vars depending on name
          # • "${val/%+('|')/}" means trim all trailing slashes from $var
          case $name in
          'file_base') file_base="$val" ;;
          'dir_files') dir_files="${val/%+('|')/}" ;;
          'url_base') url_base="${val/%+('|')/}" ;;
          'mnt_base') mnt_base="${val/%+('|')/}" ;;
          esac
        fi
      done <"$conf"
    fi
  done
  { { { ((extglob_was_set == 0)); } && shopt -s extglob; } || shopt -u extglob; }
  unset system_conf local_conf msg
}
# processOptions([@options])    {{{1
#   intent: process all command line options
#   params: @options - all command line parameters
#   prints: feedback
#   return: nil
#   note:   after execution variable @ARGS contains
#           remaining command line args (after options removed)
processOptions() {
  # read the command line options
  local OPTIONS
  if ! OPTIONS="$(
    getopt \
      --options l:u:hvd \
      --long lower:,upper:,help,verbose,debug \
      --name "${BASH_SOURCE[0]}" \
      -- "$@"
  )"; then
    # getopt displays errors
    exit 1
  fi
  eval set -- "$OPTIONS"
  while true; do
    case "$1" in
    -l | --lower)
      lower="$2"
      shift 2
      ;;
    -u | --upper)
      upper="$2"
      shift 2
      ;;
    -h | --help)
      displayUsage
      exit 0
      ;;
    -v | --verbose)
      set -o verbose
      shift 1
      ;;
    -d | --debug)
      set -o xtrace
      shift 1
      ;;
    --)
      shift
      break
      ;;
    *) break ;;
    esac
  done
}
# joinBy($delim, @items)    {{{1
#   intent: join all items using delimiter
#   params: delim - delimiter
#           items - items to be joined
#   prints: string containing joined items
#   return: nil
joinBy() {
  local delimiter first_item
  delimiter="${1:-}"
  shift
  first_item="${1:-}"
  shift
  printf %b%s "$first_item" "${@/#/$delimiter}"
}
# log($message, [$priority])    {{{1
#   intent: write message to system log
#   params: 1 - message [required]
#           2 - priority [optional, default='info']
#               can be emerg|alert|crit|err|warning|notice|info|debug
#   prints: nil
#   return: nil
log() {
  # process parameters
  local prefix
  prefix="$dn_self"
  local message
  message="$1"
  local priority
  priority="$2"
  if test -z "$priority"; then priority='info'; fi
  # log message if logger is available
  local exe
  exe='/usr/bin/logger'
  [ -x "$exe" ] && $exe --priority "user.$priority" --tag "$prefix" "$message"
}
# abort($message)    {{{1
#   intent: abort script with error message
#   params: 1 - message [required]
#   prints: nil
#   return: nil
abort() {
  log "$1" 'err'
  exit 1
}
# info($message)    {{{1
#   intent: write informational message to system log
#   params: 1 - message [required]
#   prints: nil
#   return: nil
info() {
  log "$1" 'info'
}
# }}}1

# MAIN

# check for required tools    {{{1
checkPrereqs
unset required_system_tools required_local_tools

# process configuration files    {{{1
processConfigFiles "$system_conf"
unset system_conf local_conf msg

# process command line options    {{{1
processOptions "$@"
unset parameters usage usage_indent

# check for configured values    {{{1
# - file_base
[[ -n "$file_base" ]] ||
  abort "Variable 'file_base' not configured"
# - dir_files
[[ -n "$dir_files" ]] ||
  abort "Variable 'dir_files' not configured"
[[ -d "$dir_files" ]] ||
  abort "'dir_files' directory not found: $dir_files"
# - url_base
[[ -n "$url_base" ]] ||
  abort "Variable 'url_base' not configured"
# - mnt_base
[[ -n "$mnt_base" ]] ||
  abort "Variable 'mnt_base' not configured"
[[ -d "$mnt_base" ]] ||
  abort "'mnt_base' directory not found: $mnt_base"

# check options    {{{1
dnValidPosInteger "$lower" ||
  abort "Lower iso image number ($lower) is not a positive integer"
dnValidPosInteger "$upper" ||
  abort "Upper iso image number ($upper) is not a positive integer"

# check for internet connection    {{{1
# - 8.8.8.8 = google-public-dns-a.google.com
# - 8.8.4.4 = google-public-dns-a.google.com
# - 1.1.1.1 = Cloudflare DNS resolver
# - 139.130.4.5 = ns1.tesltra.net
ping_urls=(8.8.8.8 1.1.1.1 8.8.4.4 139.130.4.5)
dnCheckInternet "${ping_urls[@]}" ||
  abort 'Unable to connect to internet'

# check for max and min iso image numbers    {{{1
# - include check for reasonableness, i.e., min > 1 and max >= 16
lower_iso_num=1000000
upper_iso_num=0
fp_base="$dir_files/$file_base"
for file in "$fp_base"*; do
  remove_prefix="${file#"${fp_base}"}"
  [[ "$remove_prefix" =~ ^([1-9][0-9]*) ]] ||
    abort "Cannot extract iso image number from file: $file"
  number="${BASH_REMATCH[1]}"
  ((number > upper_iso_num)) && upper_iso_num=$number
  ((number < lower_iso_num)) && lower_iso_num=$number
done
((lower_iso_num == 1)) ||
  abort "Lower iso image number '$lower_iso_num' is not 1"
((upper_iso_num >= min_upper_iso_num)) ||
  abort "Upper iso image number is too low ($upper_iso_num < $min_upper_iso_num)"

# override boundary iso numbers if necessary    {{{1
# - already confirmed 'lower' and 'upper' are positive integers
#   so can safely do numeric comparisons
err="is outside of iso image number range ($lower_iso_num-$upper_iso_num)"
if ((lower > 0)); then
  ((lower >= lower_iso_num)) ||
    abort "Lower bound ($lower) $err"
  ((lower <= upper_iso_num)) ||
    abort "Lower bound ($lower) $err"
fi
if ((upper > 0)); then
  ((upper >= lower_iso_num)) ||
    abort "Upper bound ($upper) $err"
  ((upper <= upper_iso_num)) ||
    abort "Upper bound ($upper) $err"
fi
unset err
if ((lower > 0)) && ((upper > 0)); then
  ((lower <= upper)) ||
    abort "Lower bound ($lower) greater than upper bound ($upper)"
fi
# - if here then presume override values, if any, are valid
((lower > 0)) && lower_iso_num="$lower"
((upper > 0)) && upper_iso_num="$upper"
info "Processing iso images $lower_iso_num to $upper_iso_num"

# check for mirror default values    {{{1
rc="$HOME/.jigdo-lite"
[ -f "$rc" ] ||
  abort "Cannot locate configuration file: $rc"
grep "^debianMirror='[^']\+'$" "$rc" &>/dev/null ||
  abort "No 'debianMirror' value in configuration file: $rc"
grep "^nonusMirror='[^']\+'$" "$rc" &>/dev/null ||
  abort "No 'debianMirror' value in configuration file: $rc"
mirror_debian="$(grep "^debianMirror='[^']\+'$" "$rc" |
  sed -e "s/^debianMirror='\([^']\{1,\}\)'$/\1/")"
mirror_nonus="$(grep "^nonusMirror='[^']\+'$" "$rc" |
  sed -e "s/^nonusMirror='\([^']\{1,\}\)'$/\1/")"
info "Using default debian mirror: $mirror_debian"
info "Using default non-us mirror: $mirror_nonus"

# process iso images in sequence    {{{1
for iso_num in $(seq "$lower_iso_num" "$upper_iso_num"); do
  # download '.jigdo' and '.template' files    {{{2
  for ext in jigdo template; do
    fname="$file_base$iso_num.$ext"
    fp="$dir_files/$fname"
    url="$url_base/$fname"
    # delete old copy of file
    [ -f "$fp" ] || abort "Cannot find existing file: $fp"
    rm "$fp" || abort "Unable to delete file: $fp"
    # download file
    wget --no-directories --directory-prefix="$dir_files" "$url" ||
      abort "Unable to download '$url' to '$dir_files'"
  done

  # rename existing iso image    {{{2
  iso_fname="$file_base$iso_num.iso"
  iso_old_fname="$file_base$iso_num-old.iso"
  iso_fp="$dir_files/$iso_fname"
  iso_old_fp="$dir_files/$iso_old_fname"
  [ -f "$iso_fp" ] ||
    abort "Cannot find existing iso image: $iso_fp"
  mv "$iso_fp" "$iso_old_fp" ||
    abort "Unable to rename iso image: $iso_fp"

  # download and assemble iso image    {{{2
  if [ "$(pwd)" != "$dir_files" ]; then
    cd "$dir_files" ||
      abort "Unable to cd to directory: $dir_files"
  fi
  jigdo_file="$file_base$iso_num.jigdo"
  jigdo-lite --scan "$iso_old_fp" --noask "$jigdo_file" ||
    abort "Jigdo unable to update iso image: $jigdo_file"

  # remount new iso file and delete old iso file    {{{2
  mnt_point="$mnt_base/$iso_num"
  umount "$mnt_point" ||
    abort "Unable to unmount mount point: $mnt_point"
  mount "$mnt_point" ||
    abort "Unable to (re)mount mount point: $mnt_point"
  rm "$iso_old_fp" ||
    abort "Unable to remove old iso image: $iso_old_fp"
  # }}}2
done

# finish message    {{{1
info "Successfully updated iso images $lower_iso_num to $upper_iso_num"
# }}}1

# vim:foldmethod=marker:
