.\" Hey, EMACS: -*- nroff -*-

.\" Filename: dn-lesspipe-update.1
.\" Author:   David Nebauer
.\" History:  2026-01-04 - created

.\" -----------------------------------------------------------------
.\" NOTES
.\" -----------------------------------------------------------------
.ig

For header (.TH), first parameter, NAME, should be all caps
Second parameter, SECTION, should be 1-8, maybe w/ subsection
Other parameters are allowed: see man(7), man(1)
Please adjust the date whenever revising the manpage.

Some roff macros, for reference:
.nh        disable hyphenation
.hy        enable hyphenation
.ad l      left justify
.ad b      justify to both left and right margins
.nf        disable filling
.fi        enable filling
.br        insert line break
.sp <n>    insert n+1 empty lines
for manpage-specific macros, see groff_man(7) and man(7)

Formatting [see groff_char (7) and man (7) for details]:
\(aq  : escape sequence for (')
\[dq] : plain double quote
\[lq] : left/open double quote
\[rq] : right/close double quote
`     : left/open single quote
'     : right/close single quote
\(em  : escape sequence for em dash
\(en  : escape sequence for en dash
\.    : escape sequence for period/dot
\(rg  : registration symbol
\(tm  : trademark symbol
\fX   : escape sequence that changes font, where 'X' can be 'R|I|B|BI'
        (R = roman/normal | I = italic | B = bold | BI = bold-italic)
\fP   : switch to previous font
        in this case '\fR' could also have been used
.B    : following arguments are boldened
.I    : following arguments are italicised
.BI   : following arguments are bold alternating with italics
.BR   : following arguments are bold alternating with roman
.IB   : following arguments are italics alternating with bold
.IR   : following arguments are italics alternating with roman
.RB   : following arguments are roman alternating with bold
.RI   : following arguments are roman alternating with italics
.SM   : following arguments are small (scaled 9/10 of the regular size)
.SB   : following arguments are small bold (not small alternating with bold)
        [note: if argument in alternating pattern contains whitespace,
               enclose in whitespace]
.RS x : indent following lines by x characters
.RE   : end indent

Bulleted list:
   A bulleted list:
   .IP \[bu] 2
   lawyers
   .IP \[bu]
   guns
   .IP \[bu]
   money
Numbered list:
   A numbered list:
   .nr step 1 1
   .IP \n[step]. 3
   lawyers
   .IP \n+[step].
   guns
   .IP \n+[step].
   money
..

.\" -----------------------------------------------------------------
.\" SETUP
.\" -----------------------------------------------------------------

.\" Macro: Format URL
.\"  usage:  .URL "http:\\www.gnu.org" "GNU Project" " of the"
.\"  params: 1 = url
.\"          2 = link text/name
.\"          3 = postamble (optional)
.\"  note:   The www.tmac macro provides a .URL macro package; this
.\"          is a local fallback in case www.tmac is unavailable
.\"  credit: man(7)
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..

.\" Prefer .URL macro from www.tmac macro package if it is available
.\"  note: In the conditional below the '\n' escape returns the value of
.\"        a register, in this the '.g'
.\"        The '.g' register is only found in GNU 'troff', and it is
.\"        assumed that GNU troff will always include the www.tmac
.\"        macro package
.if \n[.g] .mso www.tmac

.\" Macro: Ellipsis
.\"  usage: .ellipsis
.\"  note: only works at beginning of line
.de ellipsis
.cc ^
...
^cc
..

.\" String: Command name
.ds self dn-lesspipe-update

.\" -----------------------------------------------------------------
.\" MANPAGE CONTENT
.\" -----------------------------------------------------------------

.TH "DN-LESSPIPE-UPDATE" "1" "2026-01-04" "" "DN-LESSPIPE-UPDATE Manual"
.SH "NAME"
\*[self] \- update local installation of lesspipe.sh
.SH "SYNOPSIS"
.SY "\*[self]"
.SH "DESCRIPTION"
lesspipe.sh is a preprocessor for the less pager that transforms non-text files
into readable text format and can enhance readability by colorizing the output.
For more details see the project's
.URL "https://lesspipe.org/" "homepage" "."
.SS "Stow package"
lesspipe.sh is installed on the local system via a stow package located at
.IR "~/.config/dotfiles/lesspipe.sh" "."
The stow package has the following structure:
.PP
.EX
├── .bash_completion
│   └── less ++
├── .config
│   └── zshenv.d
│       └── lesspipe.sh.zsh **
└── .local
    ├── bin
    │   ├── archive_color ++
    │   ├── code2color ++
    │   ├── lesscomplete ++
    │   ├── lesspipe.sh ++
    │   ├── sxw2txt ++
    │   └── vimcolor ++
    └── share
        ├── man
        │   └── man1
        │       ├── archive_color.1 **
        │       ├── code2color.1 **
        │       ├── lesscomplete.1 **
        │       ├── lesspipe.sh.1 ++
        │       ├── sxw2txt.1 **
        │       └── vimcolor.1 **
        └── zsh
            └── completions
                └── _less ++
.EE
.PP
where files marked ** were created by me and those marked ++ are provided by
the lesspipe.sh project.
.SS "Updating"
\*[self] updates the local stow package and re-stows it. The update process
includes:
.IP \[bu] 2
Downloading (git cloning) the
.URL "https://github.com/wofr06/lesspipe" "github repository"
.IP \[bu]
Building the project files
.IP \[bu]
Copying the built project files into the stow package
.IP \[bu]
Re-stowing the package.
.PP
\*[self] does some limited checking of the built project files against the
existing stow package to detect files that have been added to the project and
files that have been removed from the project. If any such files are detected
the user is notified and has the option of cancelling the update.
.PP
All build files are located in temporary directories which are deleted when
\*[self] exits or is terminated. The only exception is when \*[self] halts due
to a SIGKILL or SIGSTOP signal.
.SH "OPTIONS"
.TP
.B "\-v  \-\-verbose"
Print input lines as they are read (equivalent to \(aqset -o verbose\(aq).
Optional.
.TP
.B "\-d  \-\-debug"
Print input lines after command expansion (equivalent to \(aqset -o
xtrace\(aq). Optional.
.TP
.B "\-h  \-\-help"
Print help text and exit. Optional.
.SH "SEE ALSO"
.BR "stow " "(1),"
.BR "less " "(1)."
.SH "AUTHOR"
\*[self] was written by
.URL "mailto:david at nebauer.org" "David Nebauer" "."
.PP
This manual page was written by
.URL "mailto:david at nebauer.org" "David Nebauer"
for the Debian project (but may be used by others).
