.\" Hey, EMACS: -*- nroff -*-

.\" Filename: navi.1
.\" Author:   David Nebauer
.\" History:  2021-05-20 - created

.\" -----------------------------------------------------------------
.\" NOTES
.\" -----------------------------------------------------------------
.ig

For header (.TH), first parameter, NAME, should be all caps
Second parameter, SECTION, should be 1-8, maybe w/ subsection
Other parameters are allowed: see man(7), man(1)
Please adjust the date whenever revising the manpage.

Some roff macros, for reference:
.nh        disable hyphenation
.hy        enable hyphenation
.ad l      left justify
.ad b      justify to both left and right margins
.nf        disable filling
.fi        enable filling
.br        insert line break
.sp <n>    insert n+1 empty lines
for manpage-specific macros, see groff_man(7) and man(7)

Formatting [see groff_char (7) and man (7) for details]:
\(aq  : escape sequence for (')
\[dq] : plain double quote
\[lq] : left/open double quote
\[rq] : right/close double quote
`     : left/open single quote
'     : right/close single quote
\(em  : escape sequence for em dash
\(en  : escape sequence for en dash
\.    : escape sequence for period/dot
\(rg  : registration symbol
\(tm  : trademark symbol
\fX   : escape sequence that changes font, where 'X' can be 'R|I|B|BI'
        (R = roman/normal | I = italic | B = bold | BI = bold-italic)
\fP   : switch to previous font
        in this case '\fR' could also have been used
.B    : following arguments are boldened
.I    : following arguments are italicised
.BI   : following arguments are bold alternating with italics
.BR   : following arguments are bold alternating with roman
.IB   : following arguments are italics alternating with bold
.IR   : following arguments are italics alternating with roman
.RB   : following arguments are roman alternating with bold
.RI   : following arguments are roman alternating with italics
.SM   : following arguments are small (scaled 9/10 of the regular size)
.SB   : following arguments are small bold (not small alternating with bold)
        [note: if argument in alternating pattern contains whitespace,
               enclose in whitespace]
.RS x : indent following lines by x characters
.RE   : end indent

Bulleted list:
   A bulleted list:
   .IP \[bu] 2
   lawyers
   .IP \[bu]
   guns
   .IP \[bu]
   money
Numbered list:
   .nr step 1 1
   A numbered list:
   .IP \n[step] 3
   lawyers
   .IP \n+[step]
   guns
   .IP \n+[step]
   money
..

.\" -----------------------------------------------------------------
.\" SETUP
.\" -----------------------------------------------------------------

.\" Macro: Format URL
.\"  usage:  .URL "http:\\www.gnu.org" "GNU Project" " of the"
.\"  params: 1 = url
.\"          2 = link text/name
.\"          3 = postamble (optional)
.\"  note:   The www.tmac macro provides a .URL macro package; this
.\"          is a local fallback in case www.tmac is unavailable
.\"  credit: man(7)
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..

.\" Prefer .URL macro from www.tmac macro package if it is available
.\"  note: In the conditional below the '\n' escape returns the value of
.\"        a register, in this the '.g'
.\"        The '.g' register is only found in GNU 'troff', and it is
.\"        assumed that GNU troff will always include the www.tmac
.\"        macro package
.if \n[.g] .mso www.tmac

.\" Macro: Ellipsis
.\"  usage: .ellipsis
.\"  note: only works at beginning of line
.de ellipsis
.cc ^
...
^cc
..

.\" String: Command name
.ds self navi

.\" -----------------------------------------------------------------
.\" MANPAGE CONTENT
.\" -----------------------------------------------------------------

.TH "NAVI" "1" "2021-05-20" "" "NAVI Manual"
.SH "NAME"
\*[self] \- an interactive cheatsheet tool for the command-line
.SH "SYNOPSIS"
.BR "\*[self] " "[FLAGS] [OPTIONS] [SUBCOMMAND]"
.SH "CONFIGURATION"
Obtain the default configuration filepath with the command:
.PP
.RS 4
navi info config-path
.RE
.PP
You can generate a config file by running:
.PP
.RS 4
navi info config-example > "$(navi info config-path)"
.RE
.PP
Please check the generated config file for more information.
.SH "DESCRIPTION"
\*[self] allows you to browse through cheatsheets (that you may write yourself
or download from maintainers) and execute commands. Suggested values for
arguments are dynamically displayed in a list.
.PP
Advantages of \*[self] include: it will spare you from knowing CLIs by heart,
it will spare you from copy-pasting output from intermediate commands, it will
make you type less, and it will teach you new one-liners.
.PP
\*[self] uses fzf, skim, or Alfred under the hood and it can be either used as
a command or as a shell widget (à la Ctrl-R).
.SH "OPTIONS"
experimental: may be removed or changed at any time
.br
deprecated: may be removed in 3 months after first being deprecated
.SS "FLAGS"
.TP
.B "\-\-best\-match"
Returns the best match.
.TP
.B "\-h  \-\-help"
Prints help information.
.TP
.B "\-\-print"
Instead of executing a snippet, prints it to stdout.
.TP
.B "\-V  \-\-version"
Prints version information.
.SS "OPTIONS"
.TP
.BI "\-\-cheatsh " "cheatsh"
Search for cheatsheets using the cheat.sh repository.
.TP
.BI "\-\-finder " "finder"
Finder application to use. Possible values:
.IR "fzf" ", " "skim" "."
.TP
.BI "\-\-fzf\-overrides " "fzf\-overrides"
Finder overrides for snippet selection.
.TP
.BI "\-\-fzf\-overrides\-var " "fzf\-overrides\-var"
Finder overrides for variable selection.
.TP
.BI "\-p  \-\-path " "path"
Colon-separated list of paths containing
.I ".cheat"
files. [env: NAVI_PATH=]
.TP
.BI "\-q  \-\-query " "query"
Query.
.TP
.BI "\-\-tag\-rules " "tag\-rules"
Comma-separated list that acts as filter for tags. Parts starting with
.I "!"
represent negation. [Experimental]
.TP
.BI "\-\-tldr " "tldr"
Search for cheatsheets using the tldr-pages repository.
.SS "SUBCOMMANDS"
.TP
.B "fn"
Performs ad-hoc, internal functions provided by navi. [Experimental]
.TP
.B "help"
Prints this message or the help of the given subcommand(s).
.TP
.B "info"
Shows info.
.TP
.B "repo"
Manages cheatsheet repositories.
.TP
.B "widget"
Outputs shell widget source code.
.SH "ENVIRONMENT"
.TP
.B "NAVI_CONFIG"
Path to configuration file.
.TP
.B "NAVI_CONFIG_YAML"
Configuration file content.
.TP
.B "NAVI_PATH"
Colon-separated list of paths containing
.I ".cheat"
files.
.SH "FILES"
.I https://github.com/denisidoro/navi
.IP
Project home of \*[self].
.SH "EXAMPLES"
navi
.PP
.RS 4
Default behavior.
.RE
.PP
navi --print
.PP
.RS 4
Doesn't execute the snippet.
.RE
.PP
navi --tldr docker
.PP
.RS 4
Search for docker cheatsheets using tldr.
.RE
.PP
navi --cheatsh docker
.PP
.RS 4
Search for docker cheatsheets using cheatsh.
.RE
.PP
navi --path '/some/dir:/other/dir'
.PP
.RS 4
Use 
.I ".cheat"
files from custom paths.
.RE
.PP
navi --query git
.PP
.RS 4
Filter results by "git".
.RE
.PP
navi --query 'create db' --best-match
.PP
.RS 4
Autoselect the snippet that best matches a query.
.RE
.PP
db=my navi --query 'create db' --best-match
.PP
.RS 4
Same, but set the value for the
.I "name"
variable.
.RE
.PP
navi repo add denisidoro/cheats
.PP
.RS 4
Import cheats from a git repository.
.RE
.PP
eval "$(navi widget zsh)"
.PP
.RS 4
Load the zsh widget.
.RE
.PP
navi --finder 'skim'
.PP
.RS 4
Set skim as finder, instead of fzf.
.RE
.PP
navi --fzf-overrides '--with-nth 1,2'
.PP
.RS 4
Show only the comment and tag columns.
.RE
.PP
navi --fzf-overrides '--no-select-1'
.PP
.RS 4
Prevent autoselection in case of single line.
.RE
.PP
navi --fzf-overrides-var '--no-select-1'
.PP
.RS 4
Same, but for variable selection.
.RE
.PP
navi --fzf-overrides '--nth 1,2'
.PP
.RS 4
Only consider the first two columns for search.
.RE
.PP
navi --fzf-overrides '--no-exact'
.PP
.RS 4
Use looser search algorithm.
.RE
.PP
navi --tag-rules='git,!checkout'
.PP
.RS 4
Show non-checkout git snippets only.
.RE
.SH "SEE ALSO"
.BR "fzf " "(1)."
