#!/bin/sh

# File: deb-dir-prepare

# Package: mail-dir-monitor

# This file will be sourced by dn-build-deb after copying customised
# debian control files to the debian package source and just prior
# to building the package. The cwd directory during the sourcing is
# '/home/david/data/computing/projects/utils/mail-dir-monitor/debianise/source/<archive>'
# where <archive> is the top-level directory in the source project
# tarzipped distribution built in 'tarball/build'.

# VARIABLES

declare xfile=""
declare xpkg="mail-dir-monitor"

# MAIN

# Variable replacement: @pkg_name@ = mail-dir-monitor
dnInfon "Inserting pkg name in control scripts... " 
for xfile in debian/* ; do
	if test -f "${xfile}" ; then
		sed -i -e "s/@pkg_name@/${xpkg}/g" "${xfile}"
	fi
done
echo "Done"
