requires 'perl', '5.038';
requires 'autodie', '2.36';
requires 'Carp', '1.54';
requires 'Const::Fast', '0.014';
requires 'File::MimeInfo', '0.35';
requires 'MIME::Base64', '3.16';
requires 'Moo', '2.005005';
requires 'MooX::Options', '4.103';
requires 'namespace::clean', '0.27';
requires 'Path::Tiny', '0.144';
requires 'strictures', '2.000006';
requires 'Types::Standard', '2.004000';
requires 'version', '0.9930';

on test => sub {
    requires 'Test::More', '0.96';
};
