#!/usr/bin/env bash

# File: dn-neomutt
# Author: David Nebauer (david at nebauer dot org)
# Purpose: Run neomutt in an alacritty terminal
# Created: 2026-02-13

# ERROR HANDLING    {{{1

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset
# Catch error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail
# Turn on traces, useful while debugging but commented out by default
# set -o xtrace

# VARIABLES    {{{1

self="$(basename "$0")"
usage='Usage:'
# shellcheck disable=SC2046
printf -v 'usage_indent' -- ' %.s' $(eval echo "{1..${#usage}}")
parameters='[-v] [-d]'
# required tools findable on system path
required_system_tools=(alacritty getopt neomutt)
# }}}1

# PROCEDURES

# checkPrereqs()    {{{1
#   intent: check for required tools
#   params: nil
#   prints: error message if tool(s) missing
#   return: n/a, aborts scipts on failure
checkPrereqs() {
  local missing tool
  missing=()
  # these tools can be found on the base system path
  for tool in "${required_system_tools[@]}"; do
    command -v "$tool" &>/dev/null || missing+=("$tool")
  done
  if [[ ${#missing[@]} -ne 0 ]]; then
    local msg
    msg="Can't run without: $(joinBy ', ' "${missing[@]}")"
    echo "$self: $msg" >/dev/stderr
    exit 1
  fi
}
# displayUsage()    {{{1
#   intent: display usage information
#   params: nil
#   prints: nil
#   return: nil
displayUsage() {
  cat <<_USAGE
$self: neomutt wrapper

Runs the command:

  alacritty \\
    --class 'AlacrittyNeomutt,AlacrittyNeomutt' \\
    --title AlacrittyNeomutt \\
    --command neomutt

$usage $self $parameters
$usage_indent $self -h

Options: -v = print input lines as they are read
              (equivalent to 'set -o verbose')
         -d = print input lines after command expansion
              (equivalent to 'set -o xtrace')
_USAGE
}
# processOptions([@options])    {{{1
#   intent: process all command line options
#   params: @options - all command line parameters
#   prints: feedback
#   return: nil
#   note:   after execution variable @ARGS contains
#           remaining command line args (after options removed)
processOptions() {
  # read the command line options
  local OPTIONS
  if ! OPTIONS="$(
    getopt \
      --options hvd \
      --long help,verbose,debug \
      --name "${BASH_SOURCE[0]}" \
      -- "$@"
  )"; then
    # getopt displays errors
    exit 1
  fi
  eval set -- "$OPTIONS"
  while true; do
    case "$1" in
    -h | --help)
      displayUsage
      exit 0
      ;;
    -v | --verbose)
      set -o verbose
      shift 1
      ;;
    -d | --debug)
      set -o xtrace
      shift 1
      ;;
    --)
      shift
      break
      ;;
    *) break ;;
    esac
  done
}
# joinBy($delim, @items)    {{{1
#   intent: join all items using delimiter
#   params: delim - delimiter
#           items - items to be joined
#   prints: string containing joined items
#   return: nil
joinBy() {
  local delimiter first_item
  delimiter="${1:-}"
  shift
  first_item="${1:-}"
  shift
  printf %b%s "$first_item" "${@/#/$delimiter}"
}
# }}}1

# MAIN

# check for required tools    {{{1
checkPrereqs
unset required_system_tools required_local_tools

# process command line options    {{{1
processOptions "$@"
unset parameters usage usage_indent

# run neomutt    {{{1
exec \
  alacritty \
  --class 'AlacrittyNeomutt,AlacrittyNeomutt' \
  --title AlacrittyNeomutt \
  --command neomutt
# }}}1

# vim:foldmethod=marker:
