.\" Hey, EMACS: -*- nroff -*-

.\" Filename: stylua.1
.\" Author:   David Nebauer
.\" History:  2025-10-05 - created

.\" -----------------------------------------------------------------
.\" NOTES
.\" -----------------------------------------------------------------
.ig

For header (.TH), first parameter, NAME, should be all caps
Second parameter, SECTION, should be 1-8, maybe w/ subsection
Other parameters are allowed: see man(7), man(1)
Please adjust the date whenever revising the manpage.

Some roff macros, for reference:
.nh        disable hyphenation
.hy        enable hyphenation
.ad l      left justify
.ad b      justify to both left and right margins
.nf        disable filling
.fi        enable filling
.br        insert line break
.sp <n>    insert n+1 empty lines
for manpage-specific macros, see groff_man(7) and man(7)

Formatting [see groff_char (7) and man (7) for details]:
\(aq  : escape sequence for (')
\[dq] : plain double quote
\[lq] : left/open double quote
\[rq] : right/close double quote
`     : left/open single quote
'     : right/close single quote
\(em  : escape sequence for em dash
\(en  : escape sequence for en dash
\.    : escape sequence for period/dot
\(rg  : registration symbol
\(tm  : trademark symbol
\fX   : escape sequence that changes font, where 'X' can be 'R|I|B|BI'
        (R = roman/normal | I = italic | B = bold | BI = bold-italic)
\fP   : switch to previous font
        in this case '\fR' could also have been used
.B    : following arguments are boldened
.I    : following arguments are italicised
.BI   : following arguments are bold alternating with italics
.BR   : following arguments are bold alternating with roman
.IB   : following arguments are italics alternating with bold
.IR   : following arguments are italics alternating with roman
.RB   : following arguments are roman alternating with bold
.RI   : following arguments are roman alternating with italics
.SM   : following arguments are small (scaled 9/10 of the regular size)
.SB   : following arguments are small bold (not small alternating with bold)
        [note: if argument in alternating pattern contains whitespace,
               enclose in whitespace]
.RS x : indent following lines by x characters
.RE   : end indent

Bulleted list:
   A bulleted list:
   .IP \[bu] 2
   lawyers
   .IP \[bu]
   guns
   .IP \[bu]
   money
Numbered list:
   A numbered list:
   .nr step 1 1
   .IP \n[step]. 3
   lawyers
   .IP \n+[step].
   guns
   .IP \n+[step].
   money
..

.\" -----------------------------------------------------------------
.\" SETUP
.\" -----------------------------------------------------------------

.\" Macro: Format URL
.\"  usage:  .URL "http:\\www.gnu.org" "GNU Project" " of the"
.\"  params: 1 = url
.\"          2 = link text/name
.\"          3 = postamble (optional)
.\"  note:   The www.tmac macro provides a .URL macro package; this
.\"          is a local fallback in case www.tmac is unavailable
.\"  credit: man(7)
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..

.\" Prefer .URL macro from www.tmac macro package if it is available
.\"  note: In the conditional below the '\n' escape returns the value of
.\"        a register, in this the '.g'
.\"        The '.g' register is only found in GNU 'troff', and it is
.\"        assumed that GNU troff will always include the www.tmac
.\"        macro package
.if \n[.g] .mso www.tmac

.\" Macro: Ellipsis
.\"  usage: .ellipsis
.\"  note: only works at beginning of line
.de ellipsis
.cc ^
...
^cc
..

.\" String: Command name
.ds self stylua

.\" -----------------------------------------------------------------
.\" MANPAGE CONTENT
.\" -----------------------------------------------------------------

.TH "STYLUA" "1" "2025-11-02" "2.3.1" "STYLUA Manual"
.SH "NAME"
\*[self] \- A utility to format Lua code
.SH "SYNOPSIS"
.BR "\*[self] " "[options] [file ...]"
.SH "DESCRIPTION"
A deterministic code formatter for Lua 5.1, 5.2, 5.3, 5.4, LuaJIT, Luau and
CfxLua/FiveM Lua. StyLua parses your Lua codebase and prints it back out from
scratch, enforcing a consistent code style.
.PP
StyLua mainly follows the
.URL "https://roblox.github.io/lua-style-guide/" "Roblox Lua Style Guide" ","
with a few deviations.
.SH "OPTIONS"
.SS "General Options"
.TP
.B "\-a  \-\-allow\-hidden"
Whether to traverse hidden files/directories.
.TP
.B "\-c  \-\-check"
Runs in \(aqcheck\(aq mode.
.TP
.BI "    \-\-color " "<val>"
Use colored output. [default: Auto] [possible values: Always, Auto, Never]
.TP
.BI "\-f  \-\-config\-path " "<path>"
Specify path to
.I "stylua.toml"
configuration file.
.TP
.BI "\-g  \-\-glob " "<glob>"
Glob patterns to test against which files to check.
.TP
.B "\-h  \-\-help"
Print help information.
.TP
.B "    \-\-lsp"
Run Stylua as a language server (following LSP protocol).
.TP
.B "    \-\-no\-editorconfig"
Disables the EditorConfig feature.
.TP
.BI "    \-\-num\-threads " "<num>"
The number of threads to use to format files in parallel. [default: 12]
.TP
.BI "    \-\-output\-format " "<format>"
Configures the diff output when using \(aqcheck\(aq mode.
[default: Standard] [possible values: Standard, Unified, Json, Summary]
.TP
.BI "    \-\-range\-end " "<byte_offset>"
An ending range to format files, given as a byte offset from the beginning of
the file.
.TP
.BI "    \-\-range\-start " "<byte_offset>"
A starting range to format files, given as a byte offset from the beginning of
the file.
.TP
.B "    \-\-respect\-ignores"
Respect
.I ".styluaignore"
and glob matching for file paths provided directly to the tool.
.TP
.B "\-s  \-\-search\-parent\-directories"
Search parent directories for stylua.toml, if not found in current directory.
Ignored if
.I "config_path"
is provided.
.TP
.BI "    \-\-stdin\-filepath " "<path>"
Specify the location of the file that is being passed into stdin.
Ignored if not taking in input from stdin.
.TP
.B "\-v  \-\-verbose"
Enables verbose output.
.TP
.B "\-V  \-\-version"
Print version information.
.TP
.B "    \-\-verify"
Verifies the output correctness after formatting.
.SS "FORMATTING OPTIONS"
.TP
.BI "\-\-call\-parentheses " "<val>"
Specify whether to apply parentheses on function calls with single string
or table arg.
[possible values: Always, NoSingleString, NoSingleTable, None, Input]
.TP
.BI "\-\-collapse\-simple\-statement " "<val>"
Specify whether to collapse simple statements.
[possible values: Never, FunctionOnly, ConditionalOnly, Always]
.TP
.BI "\-\-column\-width " "<width>"
The column width to use to attempt to wrap lines.
.TP
.BI "\-\-indent\-type " "<val>"
The type of indents to use. [possible values: Tabs, Spaces]
.TP
.BI "\-\-indent\-width " "<width>"
The width of a single indentation level.
.TP
.BI "\-\-line\-endings " "<val>"
The type of line endings to use. [possible values: Unix, Windows]
.TP
.BI "\-\-preserve\-block\-newline\-gaps " "<val>"
Specify whether to preserve leading and trailing newline gaps for blocks.
[possible values: Never, Preserve]
.TP
.BI "\-\-quote\-style " "<val>"
The style of quotes to use in string literals.
[possible values: AutoPreferDouble, AutoPreferSingle, ForceDouble, ForceSingle]
.TP
.B "\-\-sort\-requires"
Enable requires sorting.
.TP
.BI "\-\-space\-after\-function\-names " "<val>"
[possible values: Never, Definitions, Calls, Always]
.TP
.BI "\-\-syntax " "<val>"
The type of Lua syntax to parse.
[possible values: All, Lua51, Lua52, Lua53, Lua54, Luau, LuaJit, CfxLua]
.SH "SEE ALSO"
.BR "lua " "(1)."
.PP
.SH "AUTHOR"
\*[self] was written by
.URL "https://github.com/JohnnyMorganz" "JohnnyMorganz" "."
.PP
This manual page was written by
.URL "david at nebauer.org" "David Nebauer"
for the Debian project (but may be used by others).
