.\" Hey, EMACS: -*- nroff -*-

.\" Filename: neovide.1
.\" Author:   David Nebauer
.\" History:  2022-08-15 - created
.\" Modified: 2024-05-17 - update to v0.13.0

.\" -----------------------------------------------------------------
.\" NOTES
.\" -----------------------------------------------------------------
.ig

For header (.TH), first parameter, NAME, should be all caps
Second parameter, SECTION, should be 1-8, maybe w/ subsection
Other parameters are allowed: see man(7), man(1)
Please adjust the date whenever revising the manpage.

Some roff macros, for reference:
.nh        disable hyphenation
.hy        enable hyphenation
.ad l      left justify
.ad b      justify to both left and right margins
.nf        disable filling
.fi        enable filling
.br        insert line break
.sp <n>    insert n+1 empty lines
for manpage-specific macros, see groff_man(7) and man(7)

Formatting [see groff_char (7) and man (7) for details]:
\(aq  : escape sequence for (')
\[dq] : plain double quote
\[lq] : left/open double quote
\[rq] : right/close double quote
`     : left/open single quote
'     : right/close single quote
\(em  : escape sequence for em dash
\(en  : escape sequence for en dash
\.    : escape sequence for period/dot
\(rg  : registration symbol
\(tm  : trademark symbol
\fX   : escape sequence that changes font, where 'X' can be 'R|I|B|BI'
        (R = roman/normal | I = italic | B = bold | BI = bold-italic)
\fP   : switch to previous font
        in this case '\fR' could also have been used
.B    : following arguments are boldened
.I    : following arguments are italicised
.BI   : following arguments are bold alternating with italics
.BR   : following arguments are bold alternating with roman
.IB   : following arguments are italics alternating with bold
.IR   : following arguments are italics alternating with roman
.RB   : following arguments are roman alternating with bold
.RI   : following arguments are roman alternating with italics
.SM   : following arguments are small (scaled 9/10 of the regular size)
.SB   : following arguments are small bold (not small alternating with bold)
        [note: if argument in alternating pattern contains whitespace,
               enclose in whitespace]
.RS x : indent following lines by x characters
.RE   : end indent

Bulleted list:
   A bulleted list:
   .IP \[bu] 2
   lawyers
   .IP \[bu]
   guns
   .IP \[bu]
   money
Numbered list:
   .nr step 1 1
   A numbered list:
   .IP \n[step] 3
   lawyers
   .IP \n+[step]
   guns
   .IP \n+[step]
   money
..

.\" -----------------------------------------------------------------
.\" SETUP
.\" -----------------------------------------------------------------

.\" Macro: Format URL
.\"  usage:  .URL "http:\\www.gnu.org" "GNU Project" " of the"
.\"  params: 1 = url
.\"          2 = link text/name
.\"          3 = postamble (optional)
.\"  note:   The www.tmac macro provides a .URL macro package; this
.\"          is a local fallback in case www.tmac is unavailable
.\"  credit: man(7)
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..

.\" Prefer .URL macro from www.tmac macro package if it is available
.\"  note: In the conditional below the '\n' escape returns the value of
.\"        a register, in this the '.g'
.\"        The '.g' register is only found in GNU 'troff', and it is
.\"        assumed that GNU troff will always include the www.tmac
.\"        macro package
.if \n[.g] .mso www.tmac

.\" Macro: Ellipsis
.\"  usage: .ellipsis
.\"  note: only works at beginning of line
.de ellipsis
.cc ^
...
^cc
..

.\" String: Command name
.ds self neovide

.\" -----------------------------------------------------------------
.\" MANPAGE CONTENT
.\" -----------------------------------------------------------------

.TH "NEOVIDE" "1" "2024-05-17" "" "NEOVIDE Manual"
.SH "NAME"
\*[self] \- a simple graphical user interface for Neovim
.SH "SYNOPSIS"
.B "\*[self] "
.RI "[" "OPTIONS" "] [" "FILES_TO_OPEN..." "] [\-\- " "NEOVIM_ARGS..." "]"
.SH "DESCRIPTION"
A simple, no\-nonsense, cross\-platform graphical user interface for
Neovim (an aggressively refactored and updated Vim editor). Where possible
there are some graphical improvements, but functionally it should act like the
terminal UI.
.SH "ARGUMENTS"
.TP
.I FILES_TO_OPEN
Files to open. Usually plainly appended to NeoVim args, except when \-\-wsl is
used. Optional.
.TP
.I NEOVIM_ARGS
Arguments to pass down to neovim without interpreting them. Optional.
.SH "OPTIONS"
.TP
.B "\-\-fork"
Spawn a child process and leak it. [env: NEOVIDE_FORK=]
.TP
.BI "\-\-frame " "<FRAME>"
Which window decorations to use. The window might not be resizable if this is
set to
.IR "none" "."
[env: NEOVIDE_FRAME=] [default: full] [possible values: full, none]
.TP
.BI "\-\-grid " "[<GRID>]"
The initial grid size of the window [<columns>x<lines>]. Defaults to columns/
lines from init.vim/lua if no value is given. If \-\-grid is not set then it's
inferred from the window size.
.TP
.B "\-\-log"
Enables logging to a file in the current directory.
.TP
.B "\-\-maximized"
Maximize the window on startup. Not equivalent to fullscreen. [env:
NEOVIDE_MAXIMIZED=]
.TP
.BI "\-\-neovim\-bin " "<NEOVIM_BIN>"
Which NeoVim binary to invoke headlessly instead of
.B "nvim"
found on $PATH. [env: NEOVIM_BIN=/usr/local/bin/nvim.appimage]
.TP
.B "\-\-no\-fork"
Be "blocking" and let the shell persist as parent process. Takes precedence
over \-\-fork. Default.
.TP
.B "\-\-no\-idle"
Render every frame. Takes more power and cpu time but possibly helps with frame
timing issues. [env: NEOVIDE_IDLE=]
.TP
.B "\-\-no\-multigrid"
Disable the Multigrid extension (disables smooth scrolling, window animations,
and floating blur). [env: NEOVIDE_NO_MULTIGRID=]
.TP
.B "\-\-no\-srgb"
Do not request sRGB when initializing the window. May help with GPUs with weird
pixel formats. Default on Linux and macOS.
.TP
.B "\-\-no\-tabs"
Disable opening multiple files in tabs. They're still buffers.
[env: NEOVIDE_SRGB=]
.TP
.B "\-\-no\-vsync"
Do not try to request VSync on the window.
.TP
.BI "\-\-server " "<ADDRESS>"
Connect to the named pipe or socket at ADDRESS.
.TP
.BI "\-\-size " "<SIZE>"
The size of the window in pixels.
.TP
.B "\-\-srgb"
Request sRGB when initializing the window. May help with GPUs with weird pixel
formats. Default on Windows. [env: NEOVIDE_SRGB=]
.TP
.B "tabs"
Enable opening multiple files in tabs. Default. [env: NEOVIDE_TABS=]
.TP
.B "\-\-title\-hidden"
Sets title hidden for the window. [env: NEOVIDE_TITLE_HIDDEN=]
.TP
.B "\-\-vsync"
Request VSync on the window. Default. [env: NEOVIDE_VSYNC=]
.TP
.BI "\-\-wayland\-app\-id " "<WAYLAND_APP_ID>"
The app ID to show to the compositor. Wayland only. Useful for setting WM
rules. [env: NEOVIDE_APP_ID=] [default: neovide]
.TP
.B "\-\-wsl"
Run neovim inside
.URL "https://docs.microsoft.com/en-us/windows/wsl/" \
     "WSL (Windows Subsystem for Linux)"
rather than on the host. [env: NEOVIDE_WSL=]
.TP
.BI "\-\-x11\-wm\-class " "<X11_WM_CLASS>"
The class part of the X11 WM_CLASS property. X only. Useful for setting
WM rules. [env: NEOVIDE_WM_CLASS=] [default: neovide]
.TP
.BI "\-\-x11-wm\-class\-instance " "<X11_WM_CLASS_INSTANCE>"
The instance part of the X11 WM_CLASS property. X only. Useful for
setting WM rules. [env: NEOVIDE_WM_CLASS_INSTANCE=] [default: neovide]
.TP
.BR "\-h" ", " "\-\-help"
Print help.
.TP
.BR "\-V" ", " "\-\-version"
Print version.
.SH "SEE ALSO"
.BR "nvim " "(1)."
.SH "AUTHOR"
\*[self] was written by keith <keith@the-simmons.net>.
.PP
This manual page was written by David Nebauer (david at nebauer dot org)
for the Debian project (but may be used by others).
