#!/bin/sh

# File: tar-dir-prepare

# Package: 7kaa

# This file will be sourced by dn-build-deb just prior to building
# the source distribution in 'tarball/build'.  That directory is
# the cwd when this file is sourced.  Must be in same dir before
# finish.

# Some useful variables available to this file are:
#   pkg         - package name
#   root        - directory: project root
#   tar_build   - directory: <root>/tarball/build
#   tar_archive - directory: <root>/tarball/archive
#   deb_scripts - directory: <root>/debianise/scripts
#   deb_source  - directory: <root>/debianise/source
#   deb_debian  - directory: <root>/debianise/debian-files

################################################################

# VARIABLES

x_dir= x_dirs='source autotools'

# MAIN

# delete current contents of build directory
rm -fr * &>/dev/null 	|| dnEndScript 1 "Can't delete contents of:" "  '$( pwd )'"

# copy files fron 'autotools' and 'source' directories
dnInfo "Adding build files"
for x_dir in ${x_dirs} ; do
cp -r -L ../${x_dir}/* ./ 2>/dev/null 		|| dnEndScript 1 "Error copying ${x_dir} files"
done
unset x_dir x_dirs
