#!/bin/sh

# File: deb-dir-prepare

# Package: dn-mc-conf

# This file will be sourced by dn-build-deb after copying customised
# debian control files to the debian package source and just prior
# to building the package.  The cwd directory during the sourcing is
# '/home/david/data/computing/projects/utils/mc-conf/debianise/source/<archive>'
# where <archive> is the top-level directory in the source project
# tarzipped distribution built in 'tarball/build'.  Must be in same
# dir when finished.

# Some useful variables available to this file are:
#   pkg         - package name
#   root        - directory: project root
#   tar_build   - directory: <root>/tarball/build
#   tar_archive - directory: <root>/tarball/archive
#   deb_scripts - directory: <root>/debianise/scripts
#   deb_source  - directory: <root>/debianise/source
#   deb_debian  - directory: <root>/debianise/debian-files
#   source_base - directory: <root>/debianise/source/archive

####################################################################

#VARIABLES

declare xfile=""
declare xpkg="dn-mc-conf"


# MAIN

# Bug workaround: Missing 'distclean' target
#
# dh_make bug creates 'rules' file with rule calling target 'distclean'
# but that target is missing; so
# if a rule uses target 'distclean' but that target is missing,
# then delete the rule
if $( grep -F "\$(MAKE) distclean" /home/david/data/computing/projects/utils/mc-conf/debianise/debian-files/rules &>/dev/null ) ; then
	if $( grep "	distclean: " /home/david/data/computing/projects/utils/mc-conf/debianise/debian-files/rules &>/dev/null ) ; then : ; else
		dnWarn  "## BUG WORKAROUND: START ##" \
				"dh_make creates rules depending on target 'distclean'" \
				"but that target is missing." \
				"Workaround is to remove rules using target 'distclean'" \
				"with the command:" \
				"  sed -i -e '/$(MAKE) distclean/d' rules"
		cp /home/david/data/computing/projects/utils/mc-conf/debianise/debian-files/rules /home/david/data/computing/projects/utils/mc-conf/debianise/debian-files/rules.old
		dnInfon "Removing problem rules... "
		sed -i -e '/$(MAKE) distclean/d' /home/david/data/computing/projects/utils/mc-conf/debianise/debian-files/rules &>/dev/null
		diff /home/david/data/computing/projects/utils/mc-conf/debianise/debian-files/rules /home/david/data/computing/projects/utils/mc-conf/debianise/debian-files/rules.old &>/dev/null
		dnOpFail 0
		dnReport 0
		rm -f /home/david/data/computing/projects/utils/mc-conf/debianise/debian-files/rules.old &>/dev/null
		dnWarn "## BUG WORKAROUND: END ##"
	fi
fi

# Variable replacement: @pkg_name@ = dn-mc-conf
dnInfon "Inserting pkg name in control scripts... " 
for xfile in debian/* ; do
	if test -f "${xfile}" ; then
		sed -i -e "s/@pkg_name@/${xpkg}/g" "${xfile}"
	fi
done
echo "Done"
